# Generated by Django 4.1.2 on 2022-10-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slack_username", models.CharField(max_length=100)),
                ("backend", models.BooleanField()),
                ("age", models.IntegerField()),
                ("bio", models.CharField(max_length=150)),
            ],
        ),
    ]
